services:
  postgres:
    image: docker.io/postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tunez_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
